version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    restart: always
    environment:
      DB_NAME: wiki
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]

  frontend:
    build: ./client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: