name: CI wiki

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Логин в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Сборка всех сервисов через docker-compose
        run: |
          cd Wiki_Code
          docker compose build

      - name: Запуск сервисов в фоне
        run: |
          cd Wiki_Code
          docker compose up -d

      - name: Проверка работы backend
        run: curl http://localhost:5000/health

      - name: Остановка сервисов
        run: |
          cd Wiki_Code
          docker compose down
      
      - name: Пуш backend в Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: Wiki_Code/server
          file: Wiki_Code/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wiki-backend:latest

      - name: Пуш frontend в Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: Wiki_Code/client
          file: Wiki_Code/client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wiki-frontend:latest
