name: CI wiki

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Кэширование Docker
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: логин в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Билд всех контейнеров
        run: |
          docker compose -f Wiki_Code/docker-compose.yml build

      - name: Запуск контейнеров в фоне
        run: |
          docker compose -f Wiki_Code/docker-compose.yml up -d

      - name: Ожидание бэка
        run: |
          for i in {1..10}; do
            if curl --fail http://localhost:5000/health; then
              exit 0
            fi
            sleep 3
          done
          exit 1

      - name: Тест бэка
        run: |
          curl http://localhost:5000/health

      - name: Остановка контейнеров
        run: |
          docker compose -f Wiki_Code/docker-compose.yml down

  Publish-Backend:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3
      
      - name: Логин в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: билд и публикация backend
        uses: docker/build-push-action@v4
        with:
          context: Wiki_Code/server
          file: Wiki_Code/server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wiki-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/wiki-backend:${{ github.ref_name }}

  Publish-Frontend:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3
      - name: Логин в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: билд и публикация frontend
        uses: docker/build-push-action@v4
        with:
          context: Wiki_Code/client
          file: Wiki_Code/client/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wiki-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/wiki-backend:${{ github.ref_name }}